### ISSUE TITLE
Compile error in v2.20.8?

### ISSUE THREAD

**Issue by cfryanr** [tdewolff/minify#642]
It seems like the source for v2.20.8 does not compile?

When trying to compile with Golang 1.21:

```
../../.gvm/pkgsets/go1.21.3/global/pkg/mod/github.com/tdewolff/minify/v2@v2.20.8/minify/minify.go:29:26: cannot use &aspMinifier (value of type **"github.com/tdewolff/minify/v2/html".Minifier) as "github.com/tdewolff/minify/v2".Minifier value in argument to Default.Add: **"github.com/tdewolff/minify/v2/html".Minifier does not implement "github.com/tdewolff/minify/v2".Minifier (missing method Minify)
```

Also see the similar linter error messages on this recent commit in GitHub: https://github.com/tdewolff/minify/commit/5b4030cc8240edf4b87bc8d195bc3f3d1ca46f50#diff-e8de53b601839cb92c2ee710ceaec336eccfe3f07212f1de3cd7f50f3c2a9583

At first glance it seems like there is an extra `&` accidentally causing the variable to be used as a pointer to a pointer?
