### ISSUE TITLE
Issues with new tag v2.3.5

### ISSUE THREAD

**Issue by agsole-asapp** [tdewolff/minify#205]
after updating from v2.3.4 to v2.3.5 using `dep ensure` I now get 

```
go/src/asapp/vendor/github.com/tdewolff/minify/css/css.go:424:58: undefined: css.Transparent
go/src/asapp/vendor/github.com/tdewolff/minify/css/css.go:427:8: undefined: css.Box_Shadow
go/src/asapp/vendor/github.com/tdewolff/minify/css/css.go:617:118: undefined: css.Flex
```

**Comment by tdewolff** [comment]
Ah I forgot to update the `parse` dependency as well. Should be alright now!

**Comment by agsole-asapp** [comment]
thank you, worked
